List的切片是数值数据的副本；
NumPy数组的切片是数值数据的视图。

In [1]:
import numpy as np
np.random.seed(0)
xx = np.random.randint(10, size=(3, 4))
xx

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [3]:
xx1 = xx[:2, :2]
xx1

array([[5, 0],
       [7, 9]])

In [4]:
xx1[0, 0] = 666
xx1

array([[666,   0],
       [  7,   9]])

xx1的内容修改后， xx的数值也改变了

In [5]:
xx

array([[666,   0,   3,   3],
       [  7,   9,   3,   5],
       [  2,   4,   7,   6]])

##### 创建数组的副本: array.copy()

In [9]:
xx2 = xx[:2, :2].copy()
xx2

array([[666,   0],
       [  7,   9]])

In [10]:
xx2 = [[0, 0], [0, 0]]
xx2

[[0, 0], [0, 0]]

In [11]:
xx

array([[666,   0,   3,   3],
       [  7,   9,   3,   5],
       [  2,   4,   7,   6]])