In [1]:
import array
L = list(range(10))
A = array.array('i', L)
A
# 'i'是一个数据类型码，表示数据为整形

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
np.array((1, 2, 3, 4, 5), dtype = 'float32')

array([1., 2., 3., 4., 5.], dtype=float32)

嵌套列表构成多维数组

In [4]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3, 5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

创建3x3，在0-1均匀分布的随机数数组

In [10]:
np.random.random((3, 3))

array([[0.28375302, 0.77721924, 0.55719419],
       [0.14060903, 0.8724434 , 0.40317403],
       [0.18912483, 0.35016811, 0.7162283 ]])

创建3x3，[0, 10)区间的随机整型数组

In [11]:
np.random.randint(0, 10, (3, 3))

array([[9, 2, 8],
       [9, 9, 8],
       [1, 7, 6]])

创建3x3的单位矩阵

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])